apiVersion: batch/v1
kind: Job
metadata:
  name: notifyt-to-slack-when-fail
  annotations:
    argocd.argoproj.io/hook: SyncFail
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      containers:
      - name: slack-notify
        image: technosophos/slack-notify
        env:
        - name: SLACK_WEBHOOK
          valueFrom:
            secretKeyRef:
              name: slack
              key: webhook
        - name: SLACK_USERNAME
          value: ArgoCD
        - name: SLACK_TITLE
          value: Fail
        - name: SLACK_MESSAGE
          value: Fail
        - name: SLACK_COLOR
          value: "#FF0000"
      restartPolicy: Never
